name: Quickstart for GitHub Actions
on: [pull_request, push]
environment: my-environment
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo '${{ toJSON(github) }}'
      - uses: actions/checkout@v3

